### ISSUE TITLE
Success emitted twice per a request

### ISSUE THREAD

**Issue by rcpeters** [meetearnest/global-request-logger#1]
Success is emitted twice per a request/response. Is that expected behavior? Should create a mini app to simulate?

**Comment by bromanko** [comment]
That would be very helpful.
I found a case with multiple `initialize`/`end` calls where this could be true. But, I would like to ensure we've covered what you are seeing.

**Comment by rcpeters** [comment]
I have this micro app you can test with:
https://github.com/rcpeters/simple-orcid-auth-node

Might be a day or two before I have time to write something simpler.

**Comment by rcpeters** [comment]
I see the behavior with this:

        var https = require('https');
        
        globalLog = require('global-request-logger');
        globalLog.initialize(); // Setup http logging
          globalLog.on('success', function(request, response) {
            console.log('Request', request);
            console.log('Response', response);
        });
        globalLog.on('error', function(request, response) {
          console.log('Request', request);
          console.log('Response', response);
        });
        
        var options = {
          hostname: 'encrypted.google.com',
          port: 443,
          path: '/',
          method: 'GET'
        };
        
        var req = https.request(options, function(res) {
          res.on('data', function(d) {
            //process.stdout.write(d);
        
          });
        });
        req.end();
        
        req.on('error', function(e) {
          //console.error(e);
        });

**Comment by laurence-myers** [comment]
Looking at the code for https.request(), it looks like the "https" module just delegates to the "http" module. So, you'll need to add some smarts to the logging function, to tell if the logging wrapper has already been called. Or, just don't add logging to "https", and guess the protocol by inspecting the options agent.

**Comment by bromanko** [comment]
What version of node/io are you using?

**Comment by denizdogan** [comment]
For what it's worth, this is happening to me too, while trying out the snoowrap library for reddit. It would be super-helpful if this could be configured somehow.

I use Node 5.5.0 and Babel-Node 6.5.1 on Windows 7 64-bit.

**Comment by GoMino** [comment]
Hi guys, I just sent a simple pull request (https://github.com/meetearnest/global-request-logger/pull/7) fixing the problem, it works fine for me even with https request.

**Comment by bromanko** [comment]
Thanks. We will merge this in.

**Comment by jsatk** [comment]
This PR https://github.com/meetearnest/global-request-logger/pull/7 resolves this issue. Closing.
